### PR TITLE
suburban_miles

### PR DESCRIPTION
**Pull request by SlyWerewolfAJ**
## Pull request contents:
- [x] Add map
    - [x] I am the author or I have obtained permission from the author
- [ ] Remove or update existing map (give details as to what and why)
- [ ] Change to HTML/CSS
- [ ] Change to code

### CODE REVIEW

**Comment by SlyWerewolfAJ** [comment]
Hopefully this worked

**Comment by SlyWerewolfAJ** [comment]
This should most likely fix it
(Still 2 items I am unsure about)
[Camera Peep, and Table with Umbrella]

**Comment by CorySanin** [comment]
I'm still missing the following:
```
MCRBOAT 
DAJUSTSH
EFMT1   
INTLSMT1
ARRT3   
VK1209  
VEKBIKES
WIEGAND1
RMCT1A  
RAPTWWLC
VEKMTE  
D0000027
TOLSWF03
TOLSWF04
TOLSWF02
TOLSWF05
TOLSWF01
AP1AVL  
LVWTR5F 
1KRAMPTB
GFTWUMT 
HPDOCK08
KNG-DCFR
KNG-DDF 
KNG-DIRC
KNG-FDHG
KNG-FDWI
SFXMFDG1
SFXMFDG2
Ardy'sSa
c-PathTS
```
Perhaps instead of removing custom items, we could come up with a way to make them available to the servers. Custom objects could have their own repo, perhaps?

**Comment by SlyWerewolfAJ** [comment]
Let me add the Original Version then

**Comment by CorySanin** [comment]
Parks will now be submitted through [ffa-tycoon-parks](https://github.com/CorySanin/ffa-tycoon-parks).

**Pull request closed without merging**
